pub mod addr;
pub mod addresses;
pub mod audio;
pub mod core_options;
pub mod game_api;
pub mod game_mode;
pub mod image;
pub mod input;
pub mod input_script;
pub mod layout;
pub mod patch;
pub mod png;
pub mod ram_search;
pub mod rect;
pub mod rom;
pub mod screen_director;
pub mod settings;
pub mod snapshot;
pub mod touch;

pub const NDS_SCREEN_WIDTH_PX: u32 = 256;
pub const NDS_SCREEN_HEIGHT_PX: u32 = 192;
